# Generated by Django 5.2.13 on 2026-07-04 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id_anon', models.CharField(db_index=True, max_length=8)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('safety_score', models.FloatField()),
                ('layer_detected', models.IntegerField(default=1)),
                ('action_taken', models.TextField(blank=True)),
                ('therapist_notes', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='unreviewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'safety_incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
