version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend-django"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend-django"

  - package-ecosystem: "pip"
    directory: "/backend-fastapi"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend-fastapi"

  - package-ecosystem: "pub"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "flutter"
