# Generated by Django 5.2.13 on 2026-05-15 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_verification_method',
            field=models.CharField(blank=True, choices=[('id_verification', 'ID Verification'), ('card_check', 'Card Check'), ('parental_consent', 'Parental Consent')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('id_verification', 'ID Verification'), ('card_check', 'Card Check'), ('parental_consent', 'Parental Consent')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'age_verifications',
            },
        ),
        migrations.CreateModel(
            name='GuardianConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_token_hash', models.CharField(max_length=255, unique=True)),
                ('abuse_disclosed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian_consents',
            },
        ),
    ]
