# Generated by Django 5.2.13 on 2026-05-15 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def apply_rls(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        schema_editor.execute("""
            -- RLS for user_consents
            ALTER TABLE user_consents ENABLE ROW LEVEL SECURITY;
            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_consent_isolation_policy') THEN
                    CREATE POLICY user_consent_isolation_policy ON user_consents
                    USING (user_id = current_setting('app.current_user_id', true)::uuid);
                END IF;
            END $$;

            -- Append-only for consent_change_log
            DO $$ BEGIN
                -- Create a trigger function to prevent updates/deletes
                CREATE OR REPLACE FUNCTION protect_append_only_log() RETURNS trigger AS $func$
                BEGIN
                    RAISE EXCEPTION 'This log is append-only and cannot be modified or deleted.';
                END;
                $func$ LANGUAGE plpgsql;

                -- Apply to consent_change_log
                IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trig_protect_consent_log') THEN
                    CREATE TRIGGER trig_protect_consent_log
                    BEFORE UPDATE OR DELETE ON consent_change_log
                    FOR EACH ROW EXECUTE FUNCTION protect_append_only_log();
                END IF;

                -- Specific role permissions if role exists
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_role') THEN
                    REVOKE UPDATE, DELETE ON consent_change_log FROM app_role;
                END IF;
            END $$;
        """)

    def remove_rls(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        schema_editor.execute("""
            DROP TRIGGER IF EXISTS trig_protect_consent_log ON consent_change_log;
            DROP FUNCTION IF EXISTS protect_append_only_log();
            DROP POLICY IF EXISTS user_consent_isolation_policy ON user_consents;
            ALTER TABLE user_consents DISABLE ROW LEVEL SECURITY;
        """)

    operations = [
        migrations.CreateModel(
            name='ConsentChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_from_session_id', models.UUIDField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_change_log',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_transcript_retention', models.CharField(choices=[('per_session', 'Per session only'), ('30_days', '30 days'), ('1_year', '1 year'), ('indefinite', 'Indefinite')], default='per_session', max_length=20)),
                ('cross_partner_insight_sharing', models.CharField(choices=[('never', 'Never share anything with partner'), ('anonymized', 'Share anonymized themes only'), ('named', 'Share named insights')], default='never', max_length=20)),
                ('joint_session_participation', models.CharField(choices=[('not_enrolled', 'Not enrolled in joint sessions'), ('enrolled', 'Enrolled in joint sessions')], default='not_enrolled', max_length=20)),
                ('shared_relationship_context', models.CharField(choices=[('not_participating', 'Not participating'), ('read_only', 'Read only'), ('read_write', 'Read and contribute')], default='not_participating', max_length=20)),
                ('therapist_summary_access', models.BooleanField(default=False)),
                ('model_improvement_data', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_consents',
            },
        ),
        migrations.RunPython(apply_rls, remove_rls),
    ]
