# Generated by Django 6.0.7 on 2026-07-20 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.CheckConstraint(condition=models.Q(('session_transcript_retention__in', ['per_session', '30_days', '1_year', 'indefinite'])), name='ck_consent_session_transcript_retention'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.CheckConstraint(condition=models.Q(('cross_partner_insight_sharing__in', ['never', 'anonymized', 'named'])), name='ck_consent_cross_partner_insight_sharing'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.CheckConstraint(condition=models.Q(('joint_session_participation__in', ['not_enrolled', 'enrolled'])), name='ck_consent_joint_session_participation'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.CheckConstraint(condition=models.Q(('shared_relationship_context__in', ['not_participating', 'read_only', 'read_write'])), name='ck_consent_shared_relationship_context'),
        ),
    ]
