from django.urls import path

from . import views

urlpatterns = [
    path(
        "<uuid:relationship_id>/messages",
        views.messages,
        name="chat-messages",
    ),
    path(
        "<uuid:relationship_id>/messages/send",
        views.send_message,
        name="chat-send",
    ),
    path(
        "<uuid:relationship_id>/read",
        views.mark_read,
        name="chat-mark-read",
    ),
    path(
        "<uuid:relationship_id>/delivered",
        views.mark_delivered,
        name="chat-mark-delivered",
    ),
    path(
        "<uuid:relationship_id>/unread",
        views.unread_count,
        name="chat-unread",
    ),
    path(
        "<uuid:relationship_id>/assist/rephrase",
        views.assist_rephrase,
        name="chat-assist-rephrase",
    ),
    path(
        "<uuid:relationship_id>/assist/check",
        views.assist_check,
        name="chat-assist-check",
    ),
    path(
        "<uuid:relationship_id>/assist/read-coach",
        views.assist_read_coach,
        name="chat-assist-read-coach",
    ),
    path(
        "<uuid:relationship_id>/assist/nudge",
        views.assist_nudge,
        name="chat-assist-nudge",
    ),
    path(
        "<uuid:relationship_id>/assist/settings",
        views.assist_settings,
        name="chat-assist-settings",
    ),
    path(
        "assist/nudges/<uuid:nudge_id>/feedback",
        views.assist_nudge_feedback,
        name="chat-assist-feedback",
    ),
    path(
        "<uuid:relationship_id>/media",
        views.upload_media,
        name="chat-media-upload",
    ),
    path(
        "media/<uuid:media_id>",
        views.media_blob,
        name="chat-media-blob",
    ),
    path(
        "media/<uuid:media_id>/thumb",
        views.media_thumb,
        name="chat-media-thumb",
    ),
    path(
        "messages/<uuid:message_id>",
        views.delete_message,
        name="chat-delete",
    ),
    path(
        "messages/<uuid:message_id>/reactions",
        views.toggle_reaction,
        name="chat-react",
    ),
]
