# Generated by Django 6.0.7 on 2026-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='weekly_summary',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='insight_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='partner_joined_session',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='relay_message_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='session_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
