# Generated by Django 6.0.3 on 2026-04-06 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("relationship_id", models.UUIDField(blank=True, null=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
