# Generated by Django 6.0.3 on 2026-04-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_rls_policies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="auditevent",
            name="hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="prev_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
