# Generated by Django 5.2.13 on 2026-07-04 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRelationshipContext',
            fields=[
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shared_context', serialize=False, to='relationships.relationship')),
                ('named_recurring_conflicts', models.JSONField(blank=True, default=list)),
                ('agreed_goals_and_values', models.JSONField(blank=True, default=list)),
                ('repair_history', models.JSONField(blank=True, default=list)),
                ('structural_facts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_relationship_context',
            },
        ),
        migrations.RemoveConstraint(
            model_name='relationship',
            name='unique_active_relationship_a',
        ),
        migrations.RemoveConstraint(
            model_name='relationship',
            name='unique_active_relationship_b',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='dissolved_by',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='invited_at',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='partner_a_id',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='partner_b_id',
        ),
        migrations.RemoveField(
            model_name='relationshipinvite',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='relationshipinvite',
            name='inviter_id',
        ),
        migrations.RemoveField(
            model_name='relationshipinvite',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='relationshipinvite',
            name='token',
        ),
        migrations.AddField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='partner_a',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='partner_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationshipinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshipinvite',
            name='inviter',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshipinvite',
            name='token_hash',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dissolved', 'Dissolved')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='relationshipinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['partner_a', 'status'], name='relationshi_partner_3b48d8_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['partner_b', 'status'], name='relationshi_partner_4144e1_idx'),
        ),
    ]
