# Generated by Django 6.0.7 on 2026-07-19 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_sharedrelationshipcontext_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayMessage',
            fields=[
                ('relay_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_content', models.TextField()),
                ('translated_content', models.TextField(blank=True, default='')),
                ('translation_quality_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('quality_review', 'Quality Review'), ('delivered', 'Delivered'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='quality_review', max_length=20)),
                ('recipient_chose_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_relays', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_messages', to='relationships.relationship')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relay_messages',
                'indexes': [models.Index(fields=['to_user', 'status'], name='idx_relay_recipient_status'), models.Index(fields=['expires_at'], name='idx_relay_expires_at')],
            },
        ),
    ]
