# Generated by Django 5.2.13 on 2026-07-04 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0002_sharedrelationshipcontext_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JointSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING_A', 'PENDING_A'), ('PENDING_B', 'PENDING_B'), ('ACTIVE', 'ACTIVE'), ('EXITED', 'EXITED'), ('TERMINATED', 'TERMINATED')], default='PENDING_A', max_length=20)),
                ('partner_a_confirmed', models.BooleanField(default=False)),
                ('partner_b_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_joint_sessions', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_sessions', to='relationships.relationship')),
            ],
            options={
                'db_table': 'joint_sessions',
            },
        ),
        migrations.CreateModel(
            name='LangGraphSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('individual', 'individual'), ('joint', 'joint'), ('async_relay', 'async_relay')], max_length=20)),
                ('state_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langgraph_sessions', to='relationships.relationship')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langgraph_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'langgraph_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback_text', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
