# Generated by Django 6.0.7 on 2026-07-21 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_sessions', '0001_initial'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='langgraphsession',
            name='summary_preview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='langgraphsession',
            name='turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='langgraphsession',
            index=models.Index(fields=['user', '-created_at'], name='idx_lgsession_user_created'),
        ),
    ]
