# Generated by Django 5.2.13 on 2026-07-28 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('sticker', 'Sticker'), ('system', 'System')], default='text', max_length=16)),
                ('ciphertext', models.TextField(blank=True, default='')),
                ('sticker', models.CharField(blank=True, default='', max_length=64)),
                ('client_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='relationships.relationship')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.couplemessage')),
                ('sender', models.ForeignKey(blank=True, help_text='Null for system messages.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_couple_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couple_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.couplemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couple_message_reactions',
            },
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField()),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couple_read_receipts',
            },
        ),
        migrations.AddIndex(
            model_name='couplemessage',
            index=models.Index(fields=['relationship', '-created_at'], name='couple_mess_relatio_bab86e_idx'),
        ),
        migrations.AddConstraint(
            model_name='couplemessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__gt', '')), fields=('relationship', 'client_id'), name='unique_client_id_per_thread'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='couple_mess_message_d668e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='unique_reaction_per_user'),
        ),
        migrations.AddConstraint(
            model_name='readreceipt',
            constraint=models.UniqueConstraint(fields=('relationship', 'user'), name='unique_receipt_per_user'),
        ),
    ]
