# Generated by Django 5.2.13 on 2026-07-28 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAssistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist_enabled', models.BooleanField(default=True)),
                ('interception_enabled', models.BooleanField(default=True)),
                ('night_nudge_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_assist', to='relationships.relationship')),
            ],
            options={
                'db_table': 'couple_chat_assist_settings',
            },
        ),
        migrations.CreateModel(
            name='AssistNudge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('night', 'End of day'), ('opportunity', 'Opening in the conversation'), ('repair', 'Way back in after a rough exchange')], max_length=16)),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_nudges', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couple_assist_nudges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relationship', 'user', '-created_at'], name='couple_assi_relatio_78e36f_idx')],
            },
        ),
    ]
