# Generated by Django 5.2.13 on 2026-07-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatassistsettings_assistnudge'),
        ('relationships', '0004_relationship_dissolved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('covered_message_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread_summary', to='relationships.relationship')),
            ],
            options={
                'db_table': 'couple_thread_summaries',
            },
        ),
    ]
