# Generated by Django 5.2.13 on 2026-07-30 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_readreceipt_last_delivered_at'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couplemessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('sticker', 'Sticker'), ('system', 'System'), ('image', 'Image'), ('voice', 'Voice')], default='text', max_length=16),
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('voice', 'Voice')], max_length=16)),
                ('storage_key', models.CharField(max_length=255)),
                ('thumb_key', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('waveform', models.JSONField(blank=True, default=list)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript_ciphertext', models.TextField(blank=True, default='')),
                ('transcript_status', models.CharField(choices=[('skipped', 'Skipped'), ('pending', 'Pending'), ('ok', 'Ok'), ('failed', 'Failed')], default='skipped', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='relationships.relationship')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couple_message_media',
            },
        ),
        migrations.AddField(
            model_name='couplemessage',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.messagemedia'),
        ),
        migrations.AddIndex(
            model_name='messagemedia',
            index=models.Index(fields=['attached_at', 'created_at'], name='couple_mess_attache_dc0ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemedia',
            index=models.Index(fields=['relationship'], name='couple_mess_relatio_bd9b93_idx'),
        ),
    ]
