# Generated by Django 5.2.13 on 2026-07-31 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_behaviourprofile'),
        ('relationships', '0004_relationship_dissolved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouplePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couple_policy', to='relationships.relationship')),
            ],
            options={
                'db_table': 'couple_policies',
            },
        ),
    ]
