# Generated by Django 5.2.13 on 2026-07-31 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0003_couplepolicy'),
        ('relationships', '0004_relationship_dissolved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('series', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_score', to='relationships.relationship')),
            ],
            options={
                'db_table': 'connection_scores',
            },
        ),
    ]
