# Generated by Django 6.0.7 on 2026-08-02 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0004_connectionscore'),
        ('relationships', '0004_relationship_dissolved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuptureAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('is_rupture', models.BooleanField()),
                ('confidence', models.FloatField(default=0.0)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rupture_assessments', to='relationships.relationship')),
            ],
            options={
                'db_table': 'rupture_assessments',
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['relationship', 'started_at'], name='idx_rupture_rel_start')],
                'constraints': [models.UniqueConstraint(fields=('relationship', 'started_at'), name='uniq_rupture_assessment_per_window')],
            },
        ),
    ]
