# Generated by Django 5.2.13 on 2026-07-25 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('category', models.CharField(choices=[('connection', 'Connection'), ('appreciation', 'Appreciation'), ('growth', 'Growth'), ('fun', 'Fun'), ('values', 'Values'), ('intimacy', 'Intimacy')], default='connection', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementStreak',
            fields=[
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='engagement_streak', serialize=False, to='relationships.relationship')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.CharField(blank=True, default='', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'engagement_streaks',
            },
        ),
        migrations.CreateModel(
            name='MicroActionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('target_attachment_style', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'micro_action_templates',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GratitudeMoment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('gratitude', 'Gratitude'), ('repair', 'Repair')], default='gratitude', max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_moments', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gratitude_moments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('relationship', 'Relationship'), ('health', 'Health & Fitness'), ('financial', 'Financial'), ('learning', 'Learning'), ('home', 'Home & Family'), ('adventure', 'Adventure & Travel'), ('custom', 'Custom')], default='relationship', max_length=20)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('once', 'One-time')], default='daily', max_length=10)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_goals', to='relationships.relationship')),
            ],
            options={
                'db_table': 'shared_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('date_key', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='engagement.sharedgoal')),
            ],
            options={
                'db_table': 'goal_progress_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField()),
                ('date_key', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='engagement.dailyquestion')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_responses', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_question_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_question_responses',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('relationship', 'user', 'date_key'), name='uniq_daily_response_per_user_day')],
            },
        ),
        migrations.CreateModel(
            name='MicroActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_key', models.CharField(db_index=True, max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_action_logs', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_action_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='engagement.microactiontemplate')),
            ],
            options={
                'db_table': 'micro_action_logs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date_key'), name='uniq_micro_action_per_user_day')],
            },
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('daily_question', 'Answered daily question'), ('check_in', 'Daily check-in'), ('goal_progress', 'Logged goal progress'), ('micro_action', 'Completed micro-action'), ('gratitude', 'Shared gratitude'), ('repair', 'Logged a repair'), ('both_answered_bonus', 'Both partners answered'), ('streak_bonus', 'Streak milestone')], max_length=30)),
                ('date_key', models.CharField(db_index=True, max_length=10)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='points_ledg_user_id_ef075d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelationshipCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_score', models.PositiveSmallIntegerField()),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low'), ('rough', 'Rough')], default='', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('date_key', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relationship_check_ins',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('relationship', 'user', 'date_key'), name='uniq_check_in_per_user_day'), models.CheckConstraint(condition=models.Q(('connection_score__gte', 1), ('connection_score__lte', 5)), name='check_in_score_1_to_5')],
            },
        ),
        migrations.AddIndex(
            model_name='sharedgoal',
            index=models.Index(fields=['relationship', 'status'], name='shared_goal_relatio_ddd0d0_idx'),
        ),
    ]
