# Generated by Django 5.2.13 on 2026-07-25 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_solo_mode'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=280)),
                ('game_type', models.CharField(choices=[('know_your_partner', 'Know Your Partner'), ('this_or_that', 'This or That'), ('would_you_rather', 'Would You Rather'), ('two_truths', 'Two Truths & a Lie'), ('conversation_deck', 'Conversation Deck')], default='know_your_partner', max_length=30)),
                ('category', models.CharField(choices=[('relationship', 'Relationship'), ('fun', 'Fun & Quirky'), ('spiritual', 'Faith & Values'), ('financial', 'Money & Future'), ('spicy', 'Spicy')], default='relationship', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_packs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pointsledger',
            name='reason',
            field=models.CharField(choices=[('daily_question', 'Answered daily question'), ('check_in', 'Daily check-in'), ('goal_progress', 'Logged goal progress'), ('micro_action', 'Completed micro-action'), ('gratitude', 'Shared gratitude'), ('repair', 'Logged a repair'), ('both_answered_bonus', 'Both partners answered'), ('game_completed', 'Completed a couple game'), ('streak_bonus', 'Streak milestone')], max_length=30),
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='engagement.gamepack')),
            ],
            options={
                'db_table': 'game_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('self_answer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guess_answer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='engagement.gamepack')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_plays', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_plays', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='engagement.gamequestion')),
            ],
            options={
                'db_table': 'game_plays',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='uniq_game_play_per_user_question')],
            },
        ),
    ]
