# Generated by Django 5.2.13 on 2026-07-26 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0008_seed_conversation_decks'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tradition', models.CharField(choices=[('universal', 'Universal / spiritual'), ('christian', 'Christian'), ('islamic', 'Islamic'), ('jewish', 'Jewish'), ('buddhist', 'Buddhist'), ('hindu', 'Hindu')], db_index=True, default='universal', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('reflection_prompt', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_readings',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaithPractice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('tradition', models.CharField(blank=True, db_index=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faith_practices',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaithPracticeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_key', models.CharField(max_length=10)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='engagement.faithpractice')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faith_practice_logs', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faith_practice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faith_practice_logs',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'practice', 'date_key'), name='uniq_faith_practice_per_day')],
            },
        ),
        migrations.CreateModel(
            name='FaithReflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_key', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='engagement.dailyreading')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faith_reflections', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faith_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faith_reflections',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date_key'), name='uniq_faith_reflection_per_day')],
            },
        ),
    ]
