# Generated by Django 5.2.13 on 2026-07-26 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0010_seed_faith_content'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlissItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('reminder', 'Reminder'), ('event', 'Calendar event')], default='reminder', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('source', models.CharField(default='bliss', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bliss_items', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bliss_items', to='relationships.relationship')),
            ],
            options={
                'db_table': 'bliss_items',
                'ordering': ['due_at', 'created_at'],
                'indexes': [models.Index(fields=['relationship', 'status', 'due_at'], name='bliss_items_relatio_9c673b_idx')],
            },
        ),
    ]
