# Generated by Django 5.2.13 on 2026-07-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0011_blissitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blissitem',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
