# Generated by Django 5.2.13 on 2026-07-26 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0013_seed_this_or_that'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoTruthsPlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statements', models.JSONField(default=list)),
                ('lie_index', models.PositiveSmallIntegerField()),
                ('guess_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_truths_plays', to='relationships.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_truths_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_truths_plays',
                'constraints': [models.UniqueConstraint(fields=('relationship', 'user'), name='uniq_two_truths_per_user'), models.CheckConstraint(condition=models.Q(('lie_index__gte', 0), ('lie_index__lte', 2)), name='two_truths_lie_index_0_2')],
            },
        ),
    ]
