# Generated by Django 5.2.13 on 2026-07-26 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0014_twotruthsplay'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('for_partner', 'For my partner'), ('with_partner', 'With each other')], default='for_partner', max_length=12)),
                ('text', models.CharField(max_length=280)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='relationships.relationship')),
            ],
            options={
                'db_table': 'commitments',
                'ordering': ['remind_at', 'created_at'],
                'indexes': [models.Index(fields=['relationship', 'status', 'remind_at'], name='commitments_relatio_7ebe70_idx')],
            },
        ),
    ]
