# Generated by Django 5.2.13 on 2026-07-26 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0015_commitment'),
        ('relationships', '0004_relationship_dissolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('ended', 'Ended'), ('declined', 'Declined')], default='proposed', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='relationships.relationship')),
            ],
            options={
                'db_table': 'focus_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relationship', 'status'], name='focus_sessi_relatio_55b9ea_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['proposed', 'active'])), fields=('relationship',), name='uniq_live_focus_per_relationship')],
            },
        ),
    ]
