// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSqDnEEsDbyKYyQDsgKhc8GLhsiX52J2g',
    appId: '1:1038161386697:web:d5213f242c3b2f26a60118',
    messagingSenderId: '1038161386697',
    projectId: 'bliss-d7721',
    authDomain: 'bliss-d7721.firebaseapp.com',
    storageBucket: 'bliss-d7721.firebasestorage.app',
    measurementId: 'G-79978120N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYBqIKqVPRXQT73L71pWuvb5C4vMhKBsk',
    appId: '1:1038161386697:android:db32f4371d51e664a60118',
    messagingSenderId: '1038161386697',
    projectId: 'bliss-d7721',
    storageBucket: 'bliss-d7721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlMzLlr0OI6NTa_wSZtR73qB5ZqUul_c',
    appId: '1:1038161386697:ios:7c8a579218e027b4a60118',
    messagingSenderId: '1038161386697',
    projectId: 'bliss-d7721',
    storageBucket: 'bliss-d7721.firebasestorage.app',
    iosBundleId: 'ai.relationship.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlMzLlr0OI6NTa_wSZtR73qB5ZqUul_c',
    appId: '1:1038161386697:ios:7c8a579218e027b4a60118',
    messagingSenderId: '1038161386697',
    projectId: 'bliss-d7721',
    storageBucket: 'bliss-d7721.firebasestorage.app',
    iosBundleId: 'ai.relationship.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSqDnEEsDbyKYyQDsgKhc8GLhsiX52J2g',
    appId: '1:1038161386697:web:337a3c6113314612a60118',
    messagingSenderId: '1038161386697',
    projectId: 'bliss-d7721',
    authDomain: 'bliss-d7721.firebaseapp.com',
    storageBucket: 'bliss-d7721.firebasestorage.app',
    measurementId: 'G-T9ZDZ3TF9F',
  );
}
