# Generated by Django 5.2.13 on 2026-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="reinforcement_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of times this semantic memory has been reinforced",
            ),
        ),
    ]
