# Generated by Django 6.0.7 on 2026-07-20 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('partner_joined', 'Partner Joined Session'), ('relay_received', 'Relay Message Received'), ('insight_detected', 'Insight Detected'), ('safety_followup', 'Safety Follow-up'), ('therapist_connected', 'Therapist Connected'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='idx_notif_user_created'), models.Index(fields=['user_id', 'read'], name='idx_notif_user_read')],
            },
        ),
    ]
