# Generated by Django 5.2.13 on 2026-07-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('session_reminder', 'Session Reminder'), ('partner_joined', 'Partner Joined Session'), ('relay_received', 'Relay Message Received'), ('insight_detected', 'Insight Detected'), ('safety_followup', 'Safety Follow-up'), ('therapist_connected', 'Therapist Connected'), ('daily_question_ready', 'Daily Question Answers Ready'), ('partner_checked_in', 'Partner Checked In'), ('goal_progress', 'Shared Goal Progress'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
