# Generated by Django 5.2.13 on 2026-07-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('session_reminder', 'Session Reminder'), ('partner_joined', 'Partner Joined Session'), ('relay_received', 'Relay Message Received'), ('insight_detected', 'Insight Detected'), ('safety_followup', 'Safety Follow-up'), ('therapist_connected', 'Therapist Connected'), ('daily_question_ready', 'Daily Question Answers Ready'), ('partner_checked_in', 'Partner Checked In'), ('goal_progress', 'Shared Goal Progress'), ('game_ready', 'Couple Game Results Ready'), ('bliss_reminder', 'Bliss Reminder'), ('bliss_created', 'Bliss Item Created'), ('commitment_reminder', 'Commitment Reminder'), ('commitment_created', 'Commitment Created'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
